dist: trusty
os: linux

sudo: required

services:
  - docker
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE mignon_dev;'
        
language: java
jdk: openjdk8

script: bash runMignonExample.sh

after_failure: 
  - cat cromwell-executions/MIGNON/*/call-*/shard-*/execution/stderr
  - cat cromwell-executions/MIGNON/*/call-*/shard-*/execution/stdout
