dist: trusty
os: linux

sudo: required

before_install:
  - rm -rf $PWD/mignon_test_data

services:
  - docker
        
cache:
    directories:
      - $PWD/mignon_test_data

language: java
jdk: openjdk8

script: rm -rf $PWD/mignon_test_data
