dist: trusty
os: linux

sudo: required

services:
  - docker
        
language: java
jdk: openjdk8

script: bash runMignonExample.sh

after_failure: 
  - cat cromwell-executions/MIGNON/*/call-*/shard-*/execution/stderr
  - cat cromwell-executions/MIGNON/*/call-*/shard-*/execution/stdout
