dist: trusty
os: linux

sudo: required

services:
  - docker

before_install:
    
    - rm -rf $PWD/misc_cache/*
        
cache:
    directories:
      - $HOME/misc_cache

language: java
jdk: openjdk8

## travis build will check wether the WDL code behaves correctly regarding the inputs/outputs of the different inputs of the workflow.
script: java -jar $HOME/misc_cache/mignon_test_data/mignon_test_data/womtool-47.jar validate wdl/MIGNON.wdl -i tests/test_input.json
