dist: trusty
os: linux

before_install:
    - if [ ! -f "$HOME/misc_cache/womtool_47.jar" ]; then \
        curl -L --retry 15 -o "$HOME/misc_cache/womtool_47.jar" "https://github.com/broadinstitute/cromwell/releases/download/47/womtool-47.jar"; \
        fi

cache:
    directories:
      - $HOME/misc_cache

language: java
jdk: openjdk8

## travis build will check wether the WDL code behaves correctly regarding the inputs/outputs of the different inputs of the workflow.
script: java -jar $HOME/misc_cache/womtool_47.jar validate wdl/MIGNON.wdl ;
        java -jar $HOME/misc_cache/womtool_47.jar validate wdl/MIGNON.wdl -i input_templates/hisat2.json ;
        java -jar $HOME/misc_cache/womtool_47.jar validate wdl/MIGNON.wdl -i input_templates/salmon-hisat2.json ;
        java -jar $HOME/misc_cache/womtool_47.jar validate wdl/MIGNON.wdl -i input_templates/star.json ;
        java -jar $HOME/misc_cache/womtool_47.jar validate wdl/MIGNON.wdl -i input_templates/salmon-star.json ;
        java -jar $HOME/misc_cache/womtool_47.jar validate wdl/MIGNON.wdl -i input_templates/salmon.json 