dist: trusty
os: linux

sudo: required

before_install:
  - rm -rf $PWD/mignon_test_data

services:
  - docker
        
language: java
jdk: openjdk8

script: bash runMignonExample.sh

after_script: 
  - find . -type f -name "stderr" -exec cat {} \;
  - find . -type f -name "stdout" -exec cat {} \;