title: MIGNON

author: Martin Garrido Rodriguez-Cordoba

description: Bioinformatic workflow for the mechanistic integrative analysis of RNA-Seq data 
 
theme: minima

header_pages:
  - 1_installation.md
  - 2_input.md
  - 3_output.md
  - 4_advanced.md

github_username: babelomics
twitter_username: ClinicalBioinfo

google_analytics: UA-182890267-1